### ISSUE TITLE
BungeeCord 1.12.2 - NoSuchMethodError: net.md_5.bungee.protocol.packet.KeepAlive

### ISSUE THREAD

**Issue by mibby** [Krymonota/Bungee-Reconnect#4]
KeepAlive class updated in 1.12.2. Needs to be updated in Bungee-Reconnect as well?https://github.com/SpigotMC/BungeeCord/commit/0eaabdf5ca6dddd2bcdd57b77d3d02bc4967105e

```
20:17:33 [SEVERE] Sep 19, 2017 8:17:33 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by eu.the5zig.reconnect.ReconnectTask$1.operationComplete()
java.lang.NoSuchMethodError: net.md_5.bungee.protocol.packet.KeepAlive.<init>(I)V
	at eu.the5zig.reconnect.ReconnectTask$1.operationComplete(ReconnectTask.java:131)
	at eu.the5zig.reconnect.ReconnectTask$1.operationComplete(ReconnectTask.java:109)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:641)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:660)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:534)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by krusic22** [comment]
@mibby You can use my fork: https://github.com/krusic22/Bungee-Reconnect
